version: '3.3'

services:
   db:
     image: mariadb:latest
     ports: 
      - "3306:3306"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: tweets
       MYSQL_USER: user
       MYSQL_PASSWORD: password
   web_facing:
     image: web_facing
     build: 
       context: ./web_facing
     ports: 
      - "8080:8080"
   scraper:
     image: web_scraper
     build:
       context: ./scraper
     ports:
      - "3007:3007"
     depends_on:
      - db
     